apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  devops.api.two: 'test two success.'
  application.yaml: |
    test: 11111