name: devops-project-demo

env:
  PROJECT_NAME: devops-project-demo              # set this to your project's name
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - release/*

jobs:
  run-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'
          cache: 'gradle'
      - run: |
          ./gradlew clean build --parallel --build-cache -x check

  build-image:
    needs: [ run-test ]
    runs-on: self-hosted
    steps:
      - name: Login to acr
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
          build-args: jarName=build/libs/devops-project-demo-1.0.0.jar

      - name: Remove Docker image
        run: |
          docker rmi ${{ secrets.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }} --force

  deploy-dev-qa:
    needs: [ build-image ]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    strategy:
      matrix:
        environment: [ dev, qa ]
    environment: ${{ matrix.environment }}
    steps:
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_NON_PRD }}

      - name: Setup Helm
        run: |
          helm repo add nano-byte https://helm.nano-byte.net/
          helm repo update

      - name: Deploy to ${{ matrix.environment }} environment
        run: |
          helm upgrade --install ${{ env.PROJECT_NAME }} ./helm -n ${{ matrix.environment }} \
            --set "controller.hostname=${{ matrix.environment }}-devops.demo.com" --set 'image.tag=${{ github.sha }}' \
            --atomic

  deploy-integration-uat:
    needs: [ build-image ]
    runs-on: self-hosted
    strategy:
      matrix:
        environment: [ integration, uat ]
    environment: ${{ matrix.environment }}
    steps:
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_NON_PRD }}

      - name: Setup Helm
        run: |
          helm repo add nano-byte https://helm.nano-byte.net/
          helm repo update

      - name: Deploy to ${{ matrix.environment }} environment
        run: |
          helm upgrade --install ${{ env.PROJECT_NAME }} ./helm -n ${{ matrix.environment }} \
            --set "controller.hostname=${{ matrix.environment }}-devops.demo.com" --set 'image.tag=${{ github.sha }}' \
            --atomic

  deploy-prd:
    needs: [ build-image ]
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    runs-on: self-hosted
    strategy:
      matrix:
        environment: [ prd ]
    environment: ${{ matrix.environment }}
    steps:
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_PRD }}

      - name: Setup Helm
        run: |
          helm repo add nano-byte https://helm.nano-byte.net/
          helm repo update

      - name: Deploy to ${{ matrix.environment }} environment
        run: |
          helm upgrade --install ${{ env.PROJECT_NAME }} ./helm -n ${{ matrix.environment }} \
          --set "controller.hostname=devops.demo.com" --set 'image.tag=${{ github.sha }}' \
          --atomic